/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import domain.Knjiga;
import domain.Pisac;
import javax.swing.JOptionPane;
import ui.components.KnjigeTableModel;

/**
 *
 * @author Ognjen
 */
public class GlavnaFrm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GlavnaFrm.class.getName());
    private KnjigeTableModel model;
    private Pisac pisac;
    /**
     * Creates new form GlavnaFrm
     */
    public GlavnaFrm() {
       
    }
    public GlavnaFrm(Pisac pisac){
        initComponents();
        this.pisac = pisac;
        setTitle("Knjige autora: " + pisac.getIme() + " " + pisac.getPrezime());
        try {
            pripremiTabelu();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška prilikom učitavanja knjiga: " + ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            dispose();
        }
            
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKnjige = new javax.swing.JTable();
        btnNovaKnjiga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblKnjige.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKnjige.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKnjigeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKnjige);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnNovaKnjiga.setText("Dodaj knjigu");
        btnNovaKnjiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaKnjigaActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovaKnjiga, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblKnjigeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKnjigeMouseClicked
        if(evt.getClickCount() != 2){
            return;
        }
        
        int selectedRow = tblKnjige.getSelectedRow();
        
        if(selectedRow != -1){
            try{
                KnjigeTableModel modelKnjiga = (KnjigeTableModel) tblKnjige.getModel();
                Knjiga izabranaKnjiga = modelKnjiga.getKnjiga(selectedRow);
                
                if(izabranaKnjiga != null){
                    FrmRecenzije formaRecenzije = new FrmRecenzije(izabranaKnjiga);
                    formaRecenzije.setVisible(true);
                }
                
                
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Greška pri otvaranju recenzija: " + e.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            }
            
            
            
        }
        
    }//GEN-LAST:event_tblKnjigeMouseClicked

    private void btnNovaKnjigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaKnjigaActionPerformed
        FrmNovaKnjiga forma = new FrmNovaKnjiga(pisac, this);
        forma.setVisible(true);
    }//GEN-LAST:event_btnNovaKnjigaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GlavnaFrm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovaKnjiga;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKnjige;
    // End of variables declaration//GEN-END:variables

    private void pripremiTabelu() throws Exception{
        model = new KnjigeTableModel(pisac);
        tblKnjige.setModel(model);
        model.ucitajKnjige();
        
    }

    public void refreshTable() {
        try {
            model.ucitajKnjige();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri osvežavanju knjiga: " + ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    

}
